import {
  MESSAGE_CLEANUP_EXECUTION_CANDIDATE_LIMIT,
  MESSAGE_CLEANUP_PREVIEW_CANDIDATE_LIMIT,
  messageCleanupCaseWorkspaceSchema,
  messageCleanupJobDetailSchema,
  messageCleanupJobSummarySchema,
  type MessageCleanupCaseWorkspace,
  type MessageCleanupJobDetail,
  type MessageCleanupJobSummary,
} from '@drasil/contracts';

function toSummary(detail: MessageCleanupJobDetail): MessageCleanupJobSummary {
  return messageCleanupJobSummarySchema.parse(detail);
}

const completedCombinedJob = messageCleanupJobDetailSchema.parse({
  id: 'cleanup-job-combined',
  guildId: 'guild-1',
  verificationEventId: 'case-stale',
  targetUserId: 'user-100',
  requestedBy: 'admin-1',
  actorSurface: 'web_case',
  mode: 'ban_with_cleanup',
  scope: 'last_day',
  status: 'completed',
  coverage: 'ready',
  banStatus: 'succeeded',
  caseFinalizationStatus: 'failed',
  reason: 'Remove the reviewed messages and ban the case user.',
  evidenceThreadUrl: 'https://discord.com/channels/guild-1/evidence-thread-1',
  requestedWindowStart: '2026-07-14T14:00:00.000Z',
  requestedWindowEnd: '2026-07-15T14:00:00.000Z',
  previewedAt: '2026-07-15T14:00:02.000Z',
  startedAt: '2026-07-15T14:02:00.000Z',
  completedAt: '2026-07-15T14:02:08.000Z',
  failedAt: null,
  createdAt: '2026-07-15T14:00:00.000Z',
  updatedAt: '2026-07-15T14:02:08.000Z',
  lastError: 'The case was banned, but closing its Discord threads failed.',
  outcomes: {
    candidateCount: 2,
    preservedCount: 1,
    deletedCount: 1,
    alreadyMissingCount: 0,
    changedSincePreviewCount: 0,
    evidenceFailedCount: 0,
    deleteFailedCount: 0,
    permissionDeniedCount: 1,
  },
  execution: {
    canExecute: false,
    blockedReason: 'job_not_ready',
    previewCandidateLimit: MESSAGE_CLEANUP_PREVIEW_CANDIDATE_LIMIT,
    executionCandidateLimit: MESSAGE_CLEANUP_EXECUTION_CANDIDATE_LIMIT,
  },
  items: [
    {
      id: 'cleanup-item-deleted',
      messageId: 'message-101',
      channelId: 'channel-1',
      authorId: 'user-100',
      messageCreatedAt: '2026-07-15T13:45:00.000Z',
      messageEditedAt: null,
      contentPreview: 'Claim a reward at https[:]//example[.]invalid/reward',
      attachmentCount: 1,
      discoverySource: 'discord_search',
      bulkDeleteEligible: true,
      evidenceStatus: 'preserved',
      status: 'deleted',
      sourceMessageUrl: 'https://discord.com/channels/guild-1/channel-1/message-101',
      evidenceMessageUrl:
        'https://discord.com/channels/guild-1/evidence-thread-1/evidence-message-101',
      attemptedAt: '2026-07-15T14:02:02.000Z',
      evidencePreservedAt: '2026-07-15T14:02:03.000Z',
      deletedAt: '2026-07-15T14:02:04.000Z',
      completedAt: '2026-07-15T14:02:04.000Z',
      failureReason: null,
    },
    {
      id: 'cleanup-item-denied',
      messageId: 'message-102',
      channelId: 'channel-2',
      authorId: 'user-100',
      messageCreatedAt: '2026-07-15T13:50:00.000Z',
      messageEditedAt: null,
      contentPreview: 'A second reviewed message.',
      attachmentCount: 0,
      discoverySource: 'discord_search',
      bulkDeleteEligible: false,
      evidenceStatus: 'pending',
      status: 'permission_denied',
      sourceMessageUrl: 'https://discord.com/channels/guild-1/channel-2/message-102',
      evidenceMessageUrl: null,
      attemptedAt: '2026-07-15T14:02:05.000Z',
      evidencePreservedAt: null,
      deletedAt: null,
      completedAt: '2026-07-15T14:02:05.000Z',
      failureReason: 'Drasil cannot manage messages in this channel.',
    },
  ],
});

const readySourceJob = messageCleanupJobDetailSchema.parse({
  id: 'cleanup-job-source',
  guildId: 'guild-1',
  verificationEventId: 'case-stale',
  targetUserId: 'user-100',
  requestedBy: 'admin-2',
  actorSurface: 'web_case',
  mode: 'delete_only',
  scope: 'source_message',
  status: 'ready',
  coverage: 'partial',
  banStatus: 'not_requested',
  caseFinalizationStatus: 'not_applicable',
  reason: 'Remove the source message preserved in this case.',
  evidenceThreadUrl: 'https://discord.com/channels/guild-1/evidence-thread-1',
  requestedWindowStart: null,
  requestedWindowEnd: null,
  previewedAt: '2026-07-15T15:00:01.000Z',
  startedAt: null,
  completedAt: null,
  failedAt: null,
  createdAt: '2026-07-15T15:00:00.000Z',
  updatedAt: '2026-07-15T15:00:01.000Z',
  lastError: null,
  outcomes: {
    candidateCount: 1,
    preservedCount: 0,
    deletedCount: 0,
    alreadyMissingCount: 0,
    changedSincePreviewCount: 0,
    evidenceFailedCount: 0,
    deleteFailedCount: 0,
    permissionDeniedCount: 0,
  },
  execution: {
    canExecute: true,
    blockedReason: null,
    previewCandidateLimit: MESSAGE_CLEANUP_PREVIEW_CANDIDATE_LIMIT,
    executionCandidateLimit: MESSAGE_CLEANUP_EXECUTION_CANDIDATE_LIMIT,
  },
  items: [
    {
      id: 'cleanup-item-source',
      messageId: 'source-message-1',
      channelId: 'source-channel-1',
      authorId: 'user-100',
      messageCreatedAt: '2026-07-15T14:55:00.000Z',
      messageEditedAt: null,
      contentPreview: 'Reviewed source message with https[:]//example[.]invalid removed.',
      attachmentCount: 0,
      discoverySource: 'source_message',
      bulkDeleteEligible: false,
      evidenceStatus: 'pending',
      status: 'pending',
      sourceMessageUrl: 'https://discord.com/channels/guild-1/source-channel-1/source-message-1',
      evidenceMessageUrl: null,
      attemptedAt: null,
      evidencePreservedAt: null,
      deletedAt: null,
      completedAt: null,
      failureReason: null,
    },
  ],
});

export const fixtureMessageCleanupJobDetails: readonly MessageCleanupJobDetail[] = [
  readySourceJob,
  completedCombinedJob,
];

export const fixtureMessageCleanupCaseWorkspaces: readonly MessageCleanupCaseWorkspace[] = [
  messageCleanupCaseWorkspaceSchema.parse({
    guildId: 'guild-1',
    verificationEventId: 'case-stale',
    targetUserId: 'user-100',
    caseStatus: 'pending',
    evidenceThreadUrl: 'https://discord.com/channels/guild-1/evidence-thread-1',
    canPreview: true,
    blockedReason: null,
    latestJobs: fixtureMessageCleanupJobDetails.map(toSummary),
  }),
];
