/**
 * TypeScript types for database entities
 */

/**
 * Server/Guild configuration entity
 */
export interface Server {
  id: string; // UUID generated by Supabase
  guild_id: string; // Discord guild/server ID
  restricted_role_id?: string; // ID of role used for restricted users
  admin_channel_id?: string; // ID of admin notification channel
  verification_channel_id?: string; // ID of verification channel
  admin_notification_role_id?: string; // ID of role to ping for notifications
  created_at?: string; // Creation timestamp
  updated_at?: string; // Last update timestamp
  settings?: ServerSettings; // JSON blob for flexible settings
  is_active: boolean; // Whether the bot is active in this server
}

/**
 * Flexible server settings stored as JSON
 */
export interface ServerSettings {
  // Heuristic settings
  message_threshold?: number; // Max messages in timeframe
  message_timeframe?: number; // Timeframe in seconds
  suspicious_keywords?: string[]; // List of suspicious keywords

  // GPT settings
  min_confidence_threshold?: number; // Minimum confidence to flag (0-100)
  auto_restrict?: boolean; // Auto-restrict suspicious users
  use_gpt_on_join?: boolean; // Use GPT when user joins
  gpt_message_check_count?: number; // Number of messages to check with GPT

  // Retention settings
  message_retention_days?: number; // Days to keep message content
  detection_retention_days?: number; // Days to keep detection events
}

/**
 * User entity across servers
 */
export interface User {
  id: string; // UUID generated by Supabase
  discord_id: string; // Discord user ID
  username?: string; // Discord username
  created_at?: string; // Creation timestamp
  updated_at?: string; // Last update timestamp
  global_reputation_score?: number; // Cross-server reputation score
  account_created_at?: string; // When the Discord account was created
  metadata?: Record<string, unknown>; // Additional metadata
}

/**
 * Server member (user in a specific server)
 */
export interface ServerMember {
  id: string; // UUID generated by Supabase
  server_id: string; // Reference to Server.id
  user_id: string; // Reference to User.id
  join_date?: string; // When the user joined the server
  reputation_score?: number; // Server-specific reputation score
  is_restricted?: boolean; // Whether user is currently restricted
  last_verified_at?: string; // Last time user was verified
  last_message_at?: string; // Last time user sent a message
  message_count?: number; // Total message count in server
}
