const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..');
const envPath = path.join(repoRoot, '.env');

const region = process.env.AWS_REGION || 'us-east-1';
const environment = process.env.DRASIL_ENV || 'dev';
const postgresHost = process.env.POSTGRES_HOST || '127.0.0.1';
const postgresPort = process.env.POSTGRES_PORT || '54322';
const postgresDb = process.env.POSTGRES_DB || 'postgres';
const postgresUser = process.env.POSTGRES_USER || 'postgres';
const postgresPassword = process.env.POSTGRES_PASSWORD || 'postgres';

function getSecret(secretId) {
  return execFileSync(
    'aws',
    [
      'secretsmanager',
      'get-secret-value',
      '--region',
      region,
      '--secret-id',
      secretId,
      '--query',
      'SecretString',
      '--output',
      'text',
    ],
    { encoding: 'utf8' }
  ).trim();
}

function encodeUrlCredential(value) {
  return encodeURIComponent(value);
}

function quoteEnvValue(value) {
  return `"${String(value)
    .replace(/\\/g, '\\\\')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/"/g, '\\"')}"`;
}

const discordTokenSecret =
  process.env.DRASIL_DISCORD_TOKEN_SECRET || `drasil/${environment}/DISCORD_TOKEN`;
const openAiSecret = process.env.DRASIL_OPENAI_SECRET || `drasil/${environment}/OPENAI_API_KEY`;
const prismaPasswordSecret =
  process.env.DRASIL_PRISMA_PASSWORD_SECRET || `drasil/${environment}/PRISMA_DB_PASSWORD`;

const discordToken = getSecret(discordTokenSecret);
const openAiKey = getSecret(openAiSecret);
const prismaPassword = getSecret(prismaPasswordSecret);
const databaseUrl = `postgresql://prisma:${encodeUrlCredential(prismaPassword)}@${postgresHost}:${postgresPort}/${postgresDb}?schema=public`;
const postgresDbUrl = `postgresql://${encodeUrlCredential(postgresUser)}:${encodeUrlCredential(postgresPassword)}@${postgresHost}:${postgresPort}/${postgresDb}?schema=public`;

const lines = [
  '# Local Drasil environment. Gitignored.',
  `# Generated by scripts/hydrate-dev-env.js for DRASIL_ENV=${environment}.`,
  `NODE_ENV=${quoteEnvValue('development')}`,
  `DRASIL_USER_INSTALL_REPORTING_ENABLED=${quoteEnvValue(process.env.DRASIL_USER_INSTALL_REPORTING_ENABLED || 'true')}`,
  `DISCORD_TOKEN=${quoteEnvValue(discordToken)}`,
  `OPENAI_API_KEY=${quoteEnvValue(openAiKey)}`,
  `PRISMA_DB_PASSWORD=${quoteEnvValue(prismaPassword)}`,
  `DATABASE_URL=${quoteEnvValue(databaseUrl)}`,
  `POSTGRES_DB_URL=${quoteEnvValue(postgresDbUrl)}`,
  `POSTGRES_HOST=${quoteEnvValue(postgresHost)}`,
  `POSTGRES_PORT=${quoteEnvValue(postgresPort)}`,
  `POSTGRES_USER=${quoteEnvValue(postgresUser)}`,
  `POSTGRES_PASSWORD=${quoteEnvValue(postgresPassword)}`,
  `POSTGRES_DB=${quoteEnvValue(postgresDb)}`,
  '',
];

if (fs.existsSync(envPath)) {
  console.warn(`Warning: overwriting existing ${path.relative(repoRoot, envPath)}.`);
}
fs.writeFileSync(envPath, lines.join('\n'), { encoding: 'utf8', mode: 0o600 });

console.log(`Wrote ${path.relative(repoRoot, envPath)} from AWS Secrets Manager.`);
console.log(`Environment: ${environment}`);
console.log(`Region: ${region}`);
console.log(`Database: ${postgresHost}:${postgresPort}/${postgresDb}`);
console.log('Secret values were not printed.');
